# permissions for end users to view authorizationdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authorizationdomain-viewer-role
rules:
- apiGroups:
  - keycloak.open-cluster-management.io
  resources:
  - authorizationdomains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - keycloak.open-cluster-management.io
  resources:
  - authorizationdomains/status
  verbs:
  - get
