# permissions for end users to edit authorizationdomains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authorizationdomain-editor-role
rules:
- apiGroups:
  - keycloak.open-cluster-management.io
  resources:
  - authorizationdomains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - keycloak.open-cluster-management.io
  resources:
  - authorizationdomains/status
  verbs:
  - get
