apiVersion: keycloak.open-cluster-management.io/v1alpha1
kind: AuthorizationDomain
metadata:
  name: sso-ad
spec:
  identityProviders:
  - type: github
    secretRef: github-oauth-credentials
  # It should be possible to derive this URL from the Keycloak route + id of the KeycloakRealm
  issuerURL: "https://keycloak-keycloak.apps.<clusterName>.<baseDomain>/auth/realms/sso-ad"
  issuerCertificate:
    configMapRef: ca-config-map

# ---
# apiVersion: v1
# kind: Secret
# stringData:
#   clientId: <OAuthApp client ID>
#   clientSecret: <OAuthApp client secret>
# metadata:
#   name: github-oauth-credentials
